---
name: lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y \
          btrfs-progs \
          crun \
          git \
          golang-go \
          go-md2man \
          iptables \
          libassuan-dev \
          libbtrfs-dev \
          libc6-dev \
          libdevmapper-dev \
          libglib2.0-dev \
          libgpgme-dev \
          libgpg-error-dev \
          libprotobuf-dev \
          libprotobuf-c-dev \
          libseccomp-dev \
          libselinux1-dev \
          libsystemd-dev \
          pkg-config \
          uidmap
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 2m
